FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --network-timeout=100000 --no-fund --loglevel=error

# Copy the rest of the application code
COPY . .

# Expose port
EXPOSE 5004

# Start the application in development mode
CMD ["npm", "run", "dev"] 